// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.27;

import "forge-std/Test.sol";

import {Groth16Verifier_AnonNullifierTransfer} from "../src/verifiers/Verifier_AnonNullifierTransfer.sol";

// This verifier is snarkjs output, regenerated by sandbox-backend's
// regen-verifiers.sh against our locally-built zkey. It sits on the hot
// path of every Mint/Transfer; if the wrapper or constants drift the chain
// silently rejects every proof. These tests gate the contracts at the
// interface level — deploy + reject-bad-proof — without needing a real
// prover (which lives in the backend, not the ledger).
contract VerifierAnonNullifierTransferTest is Test {
    Groth16Verifier_AnonNullifierTransfer internal v;

    function setUp() public {
        v = new Groth16Verifier_AnonNullifierTransfer();
    }

    function test_Deploys() public view {
        assertGt(address(v).code.length, 0, "verifier has no code");
    }

    function test_RejectsAllZeroProof() public view {
        uint256[2] memory pA;
        uint256[2][2] memory pB;
        uint256[2] memory pC;
        uint256[7] memory pubSignals; // AnonNullifierTransfer publishes 7
        bool ok = v.verifyProof(pA, pB, pC, pubSignals);
        assertFalse(ok, "all-zero proof must not verify");
    }
}
