name: release contract artifacts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-solidity-contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: startsWith(github.ref_name, 'solidity-')
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build and package the contracts
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: ./scripts/package-contracts.sh

      - name: Upload solidity contract artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: solidity-contracts-${{ github.ref_name }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
